import { useState } from 'react'
import useDraftGuard from './useDraftGuard.jsx'
import { withDocument } from './documentUpload.js'
import { supabase } from './supabaseClient.js'
import { readTable, useCampusData, writeTable } from './campusData.js'
import { ActionForm, DataState, ModuleIntro, MutationButton } from './CampusUI.jsx'
import { officialGuides } from './officialGuides.js'

export default function AdminPanel({user,go}) {
  const state=useCampusData(async()=>({members:await readTable('member_profiles','full_name'),roles:await readTable('account_roles',null),answers:await readTable('helpdesk','question')}))
  const[editing,setEditing]=useState(null)
  const[guard,draftDialog]=useDraftGuard()
  const[query,setQuery]=useState('')
  const guidesPanel=<section className="module-panel"><h2>Official CU guidance</h2><p>Review six sourced guides covering registration, student ID, exams and transport contacts. Exact bus times still require a current university notice. Existing answers with the same question are preserved.</p><details><summary>Review guides and sources</summary>{officialGuides.map(guide=><article key={guide.question}><h3>{guide.question}</h3><p>{guide.answer}</p><a href={guide.source_url} target="_blank" rel="noreferrer">Official CU source</a></article>)}</details><MutationButton success="Official CU guides imported. Open Smart Helpdesk to read them." done={state.reload} action={async()=>{const{error}=await supabase.from('helpdesk').upsert(officialGuides,{onConflict:'question',ignoreDuplicates:true});if(error)throw error}}>Import official CU guides</MutationButton></section>
  return <div className="admin-page">{draftDialog}<ModuleIntro eyebrow="Administration" title="Campus control room">Manage trusted staff, publish Helpdesk answers and keep campus information current.</ModuleIntro><div className="module-tabs"><button onClick={()=>go('transportation')}>Transportation</button><button onClick={()=>go('notices')}>Campus notices</button><button onClick={()=>go('courses')}>Courses & attendance</button><button onClick={()=>go('events')}>Events</button><button onClick={()=>go('lostfound')}>Complaints</button></div>{guidesPanel}<DataState state={state}>{state.data&&<>
    <section className="module-panel"><h2>{editing?'Edit Helpdesk answer':'Publish Helpdesk information'}</h2><ActionForm key={editing?.id||'new'} submit={editing?'Save changes':'Publish answer'} onDone={()=>{setEditing(null);state.reload()}} onSubmit={values=>withDocument(values,user.id,fields=>writeTable('helpdesk',{...fields,keywords:fields.keywords.split(',').map(t=>t.trim()).filter(Boolean),source_url:fields.source_url||null,updated_at:new Date().toISOString()},editing?.id),editing||{})}><label>Question / notice heading<input name="question" required maxLength={300} defaultValue={editing?.question||''}/></label><label>Answer / notice details<textarea name="answer" required rows={6} defaultValue={editing?.answer||''}/></label><label>Topic<select name="category" defaultValue={editing?.category||'general'}>{['bus','exam','rules','academic','general'].map(t=><option key={t}>{t}</option>)}</select></label><label>Search keywords (comma separated)<input name="keywords" defaultValue={editing?.keywords?.join(', ')||''}/></label><label>Source name<input name="source_label" required defaultValue={editing?.source_label||'City University notice'}/></label><label>Official source link (optional)<input type="url" name="source_url" defaultValue={editing?.source_url||''}/></label><label>Attach notice / routine (optional, up to 20 MB)<input name="attachment" type="file" accept=".pdf,.docx,.pptx,.jpg,.jpeg,.png,.webp"/></label></ActionForm>{editing&&<button className="section-link" onClick={()=>guard(()=>setEditing(null))}>Cancel editing</button>}</section>
    <details className="module-panel"><summary>Published Helpdesk answers · {state.data.answers.length}</summary>{state.data.answers.map(answer=><div className="admin-answer" key={answer.id}><strong>{answer.question}</strong><button className="section-link" onClick={()=>guard(()=>{setEditing(answer);window.scrollTo({top:0,behavior:'smooth'})})}>Edit</button><MutationButton confirm="Remove this Helpdesk answer?" action={async()=>{const{error}=await supabase.from('helpdesk').delete().eq('id',answer.id);if(error)throw error}} done={state.reload}>Remove answer</MutationButton></div>)}</details>
    <section className="module-panel"><h2>Account permissions</h2><p>New accounts are students. Assign staff access only to verified university staff.</p><label className="helpdesk-search">Find a member<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, student ID or department"/></label>{state.data.members.filter(m=>`${m.full_name} ${m.department} ${m.student_number||""} ${m.id}`.toLowerCase().includes(query.toLowerCase())).map(member=>{
      const role=state.data.roles.find(r=>r.user_id===member.id)?.role||'student'
      return <details key={member.id} className="admin-member"><summary>{member.full_name} · {role}</summary><p>{member.department}</p><code>{member.id}</code>{role==="student"&&<ActionForm reset={false} submit="Save university student ID" success="University student ID saved." onDone={state.reload} onSubmit={async values=>{const number=values.student_number.trim().toUpperCase();if(number&&!/^[A-Z0-9][A-Z0-9/-]{1,49}$/.test(number))throw new Error("Use 2–50 letters, numbers, hyphens or slashes for the student ID.");const{error}=await supabase.from("member_profiles").update({student_number:number||null}).eq("id",member.id).select().single();if(error)throw error}}><label>Verified university student ID<input name="student_number" maxLength={50} defaultValue={member.student_number||""} placeholder="Enter the actual ID from university records"/></label><p className="module-muted">Each ID must be unique. Leave blank to remove an incorrect assignment.</p></ActionForm>}{member.id===user.id?<p>You are signed in with this admin account.</p>:<ActionForm submit="Update role" onDone={state.reload} onSubmit={async values=>{const{data,error}=await supabase.from('account_roles').update({role:values.role}).eq('user_id',member.id).select().single();if(error)throw error;if(!data)throw new Error('No role was updated.')}}><label>Account role<select name="role" defaultValue={role}><option>student</option><option>teacher</option><option>admin</option></select></label></ActionForm>}</details>
    })}</section>
  </>}</DataState></div>
}
