import { useEffect, useRef } from 'react'
import CampusIcon from './CampusIcon.jsx'

const descriptions={resources:['Resource Hub','A little knowledge goes a long way.','Search by course, find notes and past papers, preview PDFs and download what you need. Keep useful material in your saved collection.',['Search & filters','Private or shared uploads','Previews & downloads']],helpdesk:['Smart Helpdesk','Good questions deserve thoughtful answers.','Explore sourced campus guidance, ask a private question and continue the conversation with teachers or administrators.',['Sourced guidance','Private questions','Staff replies']],events:['Clubs & Events','Make room for something memorable.','Discover real activities published by campus staff, register for an event and keep your unique QR ticket ready for entry.',['Event discovery','Registration','QR entry tickets']],lostfound:['Student support','A helping hand, when you need one.','Share a lost or found item with the campus community, or submit a concern privately and follow administrator responses.',['Photo item reports','Private complaints','Track progress']]}
export default function DestinationPreview({destination,onClose,go}) {
  const ref=useRef(null)
  useEffect(()=>{const previous=document.activeElement;const dialog=ref.current;dialog.showModal();return()=>{dialog.close();previous?.focus()}},[])
  const [title,heading,body,features]=descriptions[destination]
  return <dialog ref={ref} className="destination-dialog" aria-labelledby="destination-heading" onCancel={event=>{event.preventDefault();onClose()}}><button className="preview-close" aria-label="Close module preview" onClick={onClose}><CampusIcon name="close"/></button><span className="preview-icon"><CampusIcon name={destination} size={34}/></span><span className="eyebrow">{title} · feature preview</span><h2 id="destination-heading">{heading}</h2><p>{body}</p><ul>{features.map(feature=><li key={feature}><CampusIcon name="check" size={16}/>{feature}</li>)}</ul><div className="preview-actions"><button className="button button-primary" onClick={()=>go('signup')}>Create your account <CampusIcon name="arrow" size={18}/></button><button className="button button-secondary" onClick={()=>go('login')}>Log in</button></div><small>Sign in to use actual campus content. This is an introduction, not live activity.</small></dialog>
}
