import { useEffect, useRef, useState } from 'react'
import CampusIcon from './CampusIcon.jsx'
import CampusScene from './CampusScene.jsx'
import DestinationPreview from './DestinationPreview.jsx'
import useActivityHeader from './useActivityHeader.js'

const chapters=[['prepare','01','Prepare','A little more ready.','Find course material, read notices and keep useful knowledge close. Start your day with a clearer next step.','resources'],['participate','02','Participate','A little more involved.','Discover campus activities, register for your place and bring your QR ticket. There’s more to university than the classroom.','events'],['support','03','Get support','A little more supported.','Ask staff a question, reconnect a lost belonging with its owner, or raise a concern privately. Help has a home here.','helpdesk']]
const shelves={Notes:['Notes worth keeping.','Share and discover course material, organized by department, course and tags.'],Papers:['A clearer way to prepare.','Search the archive for uploaded past papers. Preview PDFs before downloading.'],Slides:['Knowledge beyond the lecture.','Find shared presentations and lab material. Save useful resources on your browser.']}

export default function Landing({go}) {
  const {header,idle,wake}=useActivityHeader()
  const world=useRef(null)
  const [destination,setDestination]=useState(null)
  const [chapter,setChapter]=useState('prepare')
  const [shelf,setShelf]=useState('Notes')
  const story=useRef(null)
  useEffect(()=>{
    if(!window.IntersectionObserver||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return
    const elements=world.current.querySelectorAll('.world-section-heading,.world-feature,.community-roles article,.world-join')
    elements.forEach(element=>element.classList.add('scroll-reveal'))
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('is-visible',entry.isIntersecting)),{threshold:.08})
    elements.forEach(element=>observer.observe(element))
    return()=>{observer.disconnect();elements.forEach(element=>element.classList.remove('scroll-reveal','is-visible'))}
  },[])
  useEffect(()=>{
    if(typeof IntersectionObserver==='undefined')return
    const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio);if(visible.length)setChapter(visible[0].target.dataset.chapter)}, {rootMargin:'-15% 0px -20% 0px',threshold:[.2,.5,.8]})
    story.current.querySelectorAll('[data-chapter]').forEach(element=>observer.observe(element))
    return()=>observer.disconnect()
  },[])
  return <div className="world-landing" ref={world}><a href="#world-main" className="skip-link">Skip to content</a>{destination&&<DestinationPreview destination={destination} onClose={()=>setDestination(null)} go={go}/>}
    <header ref={header} onFocus={wake} onMouseEnter={wake} className={`world-nav world-width ${idle?'is-idle':''}`}><a href="#" className="world-brand" aria-label="CampusOS home"><span>C</span><div><strong>CampusOS</strong><small>CITY UNIVERSITY</small></div></a><nav aria-label="Explore CampusOS"><a href="#campus-day">A campus day</a><a href="#modules">The possibilities</a></nav><div><button className="world-login" onClick={()=>go('login')}>Log in <CampusIcon name="arrow" size={16}/></button><button className="button button-primary" onClick={()=>go('signup')}>Join CampusOS</button></div></header>
    <main id="world-main"><section className="world-hero world-width"><div className="hero-topline"><span><i/> CITY UNIVERSITY, A LITTLE CLOSER</span><span>Made for your everyday.</span></div><div className="world-hero-title"><h1>Your campus.<br/>A world of <em>possibilities.</em></h1><span className="hero-orbit" aria-hidden="true">✳</span></div><p className="world-hero-intro">The knowledge you share. The people you meet. <br/>The helping hand you need. Welcome to CampusOS.</p><div className="world-hero-actions"><button className="button button-primary" onClick={()=>go('signup')}>Find your place <CampusIcon name="arrow" size={18}/></button><a href="#modules">Explore the possibilities <span>↗</span></a></div><CampusScene onChoose={setDestination}/><div className="world-hero-bottom"><span><CampusIcon name="location" size={16}/> Rooted in City University, Savar</span><a href="#campus-day">A campus day, reimagined ↓</a></div></section>
      <section id="campus-day" className="world-day" ref={story}><div className="world-width"><div className="world-section-heading"><span className="eyebrow">From your first class to your next adventure</span><h2>Move through your day.<br/><em>Feel a little more connected.</em></h2></div><div className="world-day-layout"><div className="world-day-scene"><div className="day-scene-top"><span>A CAMPUS DAY</span><nav aria-label="Campus day chapters">{chapters.map(([id,,title])=><a key={id} href={`#chapter-${id}`} aria-current={chapter===id?'step':undefined} onClick={()=>setChapter(id)}>{title}</a>)}</nav></div><CampusScene compact active={chapters.find(([id])=>id===chapter)[5]}/><p className="day-caption"><span>✳</span> {chapters.find(([id])=>id===chapter)[3]}</p></div><div className="world-chapters">{chapters.map(([id,n,title,heading,body,module])=><article key={id} id={`chapter-${id}`} data-chapter={id} className={chapter===id?'chapter-current':''}><span>{n} / {title}</span><h3>{heading}</h3><p>{body}</p><button className="world-inline-link" onClick={()=>setDestination(module)}>Discover how <CampusIcon name="arrow" size={17}/></button></article>)}</div></div></div></section>
      <section className="world-features world-width" id="modules"><div className="world-section-heading"><span className="eyebrow">Four places. So many possibilities.</span><h2>Small moments.<br/><em>A better campus experience.</em></h2></div>
        <article className="world-feature feature-library"><div className="feature-copy"><span className="feature-number">01 / RESOURCE HUB</span><h3>A shelf for<br/><em>shared knowledge.</em></h3><p>Good notes deserve a good home. Find material by course, share something useful and keep your next download within reach.</p><button className="world-inline-link" onClick={()=>setDestination('resources')}>Step into the library <CampusIcon name="arrow" size={18}/></button></div><div className="library-illustration"><div className="feature-illustration-label">HOW IT WORKS / ILLUSTRATION</div><div role="tablist" aria-label="Resource introduction" onKeyDown={event=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(event.key))return;event.preventDefault();const keys=Object.keys(shelves);const index=event.key==="Home"?0:event.key==="End"?2:(keys.indexOf(shelf)+(event.key==="ArrowLeft"?2:1))%3;setShelf(keys[index]);event.currentTarget.querySelectorAll("button")[index].focus()}}>{Object.keys(shelves).map(key=><button role="tab" tabIndex={shelf===key?0:-1} id={`shelf-tab-${key}`} aria-controls="shelf-description" aria-selected={shelf===key} key={key} onClick={()=>setShelf(key)}>{key}</button>)}</div><div className="book-shelf" aria-hidden="true"><div className="shelf-book"><span>SHARED<br/>KNOWLEDGE</span><CampusIcon name="resources" size={30}/></div><div className="shelf-book"><span>{shelf.toUpperCase()}</span></div><div className="shelf-book"><span>YOUR NEXT<br/>GOOD IDEA</span><span>✳</span></div><div className="shelf-line"/></div><div role="tabpanel" id="shelf-description" aria-labelledby={`shelf-tab-${shelf}`}><h4>{shelves[shelf][0]}</h4><p>{shelves[shelf][1]}</p></div></div></article>
        <article className="world-feature feature-conversation"><div className="conversation-illustration"><span className="feature-illustration-label">THE CONVERSATION / ILLUSTRATION</span><div className="conversation-bubble"><CampusIcon name="profile" size={24}/><span>You bring<br/><strong>the question.</strong></span><span>?</span></div><div className="conversation-thread" aria-hidden="true">↓</div><div className="conversation-bubble staff-bubble"><CampusIcon name="helpdesk" size={24}/><span>Campus staff bring<br/><strong>a helping hand.</strong></span><span>✳</span></div><small>Private questions · teacher & admin replies</small></div><div className="feature-copy"><span className="feature-number">02 / SMART HELPDESK</span><h3>A good question.<br/><em>A clearer next step.</em></h3><p>Read sourced campus guidance, ask privately and follow up with staff. You shouldn’t have to figure everything out alone.</p><button className="world-inline-link" onClick={()=>setDestination('helpdesk')}>Meet your Helpdesk <CampusIcon name="arrow" size={18}/></button></div></article>
        <article className="world-feature feature-ticket"><div className="feature-copy"><span className="feature-number">03 / CLUBS & EVENTS</span><h3>Be there.<br/><em>Be part of it.</em></h3><p>Workshops, contests and campus gatherings. Discover what staff have published, register for your place and bring your QR entry ticket.</p><button className="world-inline-link" onClick={()=>setDestination('events')}>Find your next experience <CampusIcon name="arrow" size={18}/></button></div><div className="illustration-ticket"><span className="ticket-corner">CAMPUSOS / CAMPUS LIFE</span><span className="ticket-sun" aria-hidden="true">✳</span><strong>Your next<br/><em>“I was there.”</em></strong><div className="ticket-perforation"/><div className="ticket-bottom"><div><span>DISCOVER. REGISTER. JOIN.</span><small>Illustration · not an entry ticket</small></div><div className="ticket-motif" aria-hidden="true">{Array.from({length:25},(_,index)=><i key={index}/>)}</div></div></div></article>
        <article className="world-feature feature-support"><div className="support-illustration"><div className="support-orbit" aria-hidden="true"><CampusIcon name="lostfound" size={60}/><span>✳</span></div><div><span><CampusIcon name="lostfound" size={20}/> Lost & found</span><span><CampusIcon name="lock" size={20}/> Private complaints</span></div></div><div className="feature-copy"><span className="feature-number">04 / STUDENT SUPPORT</span><h3>A campus that<br/><em>looks out for you.</em></h3><p>Help a belonging find its way home. Or raise a concern through a private channel and follow its progress. Different needs, thoughtful support.</p><button className="world-inline-link" onClick={()=>setDestination('lostfound')}>Find a helping hand <CampusIcon name="arrow" size={18}/></button></div></article>
      </section>
      <section className="world-community"><img src="/images/campus/City_University_Campus_in_Bloom.png" alt="City University campus surrounded by trees" width="1200" height="700" loading="lazy"/><div className="world-width"><span className="eyebrow">A place for all of us</span><h2>Different roles.<br/><em>One community.</em></h2><div className="community-roles">{[['profile','Students','Explore, share, participate and get support.'],['courses','Teachers','Share course updates and record attendance.'],['admin','Administrators','Maintain campus information and manage access.']].map(([icon,title,body])=><article key={title}><CampusIcon name={icon}/><h3>{title}</h3><p>{body}</p></article>)}</div><p className="community-note">Teacher and Admin choices are requests. Staff permissions are assigned by an administrator.</p></div></section>
      <section className="world-join world-width"><span className="join-flower" aria-hidden="true">✳</span><span className="eyebrow">Your campus passport is waiting</span><h2>Make yourself<br/><em>part of the story.</em></h2><p>A little knowledge. A new connection. A useful next step.<br/>Begin your CampusOS journey.</p><button className="button button-primary" onClick={()=>go('signup')}>Create your account <CampusIcon name="arrow" size={18}/></button><button className="world-inline-link" onClick={()=>go('login')}>Already here? Log in ↗</button></section>
    </main><footer className="world-footer world-width"><a className="world-brand" href="#"><span>C</span><div><strong>CampusOS</strong><small>CITY UNIVERSITY</small></div></a><p>Made for campus life.<br/>Made for you.</p><span>© {new Date().getFullYear()} CampusOS</span></footer>
  </div>
}

