// Official CU sources checked 8 October 2026. These are paraphrases.
export const officialGuides = [
  { question: 'Where can I confirm CU bus routes and departure times?', category: 'bus', answer: 'Contact the University Transport Office for current routes and schedules. CU’s transport page describes buses and shuttles but does not publish exact stops or departure times. Check the latest dated transport notice before travelling.', source_url: 'https://www.cityuniversity.ac.bd/transportfacilities', keywords: ['bus', 'transport', 'shuttle', 'route', 'schedule'] },
  { question: 'How do I register for the next semester?', category: 'academic', answer: 'Pay the registration fee within the semester Academic Calendar deadline. CU advises regular students to enroll online two days after payment. Contact your Academic Advisor for registration or advising problems.', source_url: 'https://www.cityuniversity.ac.bd/registration-procedures', keywords: ['registration', 'semester', 'fees', 'advisor'] },
  { question: 'How do I add, drop or change a course section?', category: 'academic', answer: 'Request Academic Advisor permission within the Semester Calendar deadline. Dropping after the deadline without Dean permission can mean paying tuition and receiving an F grade. Confirm the current deadline with your department.', source_url: 'https://www.cityuniversity.ac.bd/registration-procedures', keywords: ['add', 'drop', 'section', 'deadline'] },
  { question: 'What should I do if I lose my student ID card?', category: 'rules', answer: 'Immediately report the loss to the Registrar’s Office so the card can be cancelled. Apply there for a duplicate card and pay the applicable fee. A CampusOS lost-item post does not replace reporting the loss to the Registrar.', source_url: 'https://www.cityuniversity.ac.bd/academic-rule-procedure', keywords: ['id', 'card', 'lost', 'registrar'] },
  { question: 'Where do I confirm my examination routine?', category: 'exam', answer: 'CU’s exam policy provides for an examination routine for each department. Confirm your course, date, time and room against the latest department-approved routine and check subsequent changes. This policy page is not a current examination timetable.', source_url: 'https://www.cityuniversity.ac.bd/exams-result-policy', keywords: ['exam', 'routine', 'room', 'timetable'] },
  { question: 'What if I miss a final examination?', category: 'exam', answer: 'Contact your course teacher promptly. CU’s published policy allows an incomplete grade for an accepted reason and describes a makeup final within four weeks of the new semester. Approval is required; confirm eligibility and the actual date with your department.', source_url: 'https://www.cityuniversity.ac.bd/exams-result-policy', keywords: ['missed', 'final', 'makeup', 'incomplete'] },
].map(guide => ({ ...guide, source_label: 'City University official website · checked 8 Oct 2026' }))
